version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge